### ISSUE TITLE
fails to login using ssh

### ISSUE THREAD

**Issue by Mrwerdo** [SFTtech/kevin#35]
I'm trying to get Kevin, Falk and Chantal to work together to login to the guest vm, but I haven't been able to get this to work yet.

Setup:
- Both the guest and host machines are macOS, the guest is running permanently inside of VMware Fusion.
- falk, kevin and kevin.simulator are running on the host machine
- ssh keys are stored in `~/.ssh/kevin-keys` and ssh is configured to use them
- The configuration files are here: [kevin.zip](https://github.com/SFTtech/kevin/files/2212085/kevin.zip)

The console output of running falk, kevin, and kevin.simulator is [here](https://github.com/SFTtech/kevin/files/2212082/log.txt)

I can login to the guest vm by running `ssh chantal@chantal.local` without providing a password, so I'm not sure why it's not working. Any help is appreciated.

**Comment by TheJJ** [comment]
According to the log, it's calling this for the ssh connection:
```
ssh -q -o UserKnownHostsFile=/var/folders/sh/1rbpyrv946j8wzbd5dyr4r8h0000gq/T/tmpiwcxpgu5 -o StrictHostKeyChecking=yes -p 22 chantal@chantal.local -- true
```

This is run as the same user as kevin is being run.
Does the simplified command work?

```
ssh -p 22 chantal@chantal.local -- true
```

What address is `chantal.local`? Is `ssh` really listening on `22` on that host? Or did you customize the port in the `.ssh/config`?

**Comment by Mrwerdo** [comment]
`chantal.local` points to `192.168.107.129`, the host is on `192.168.107.1`. Running `ssh -p 22 chantal@chantal.local -- true` works (`echo $?` prints `0`). `ssh` is really running on port 22 on the virtual machine, I've verified it with a port scanner.

The relevant portions of my `~/.ssh/config` file is the following:

    Host chantal@chantal.local
        User chantal
        HostName chantal.local
        IdentityFile ~/.ssh/kevin-keys/id_rsa

**Comment by Mrwerdo** [comment]
I just added -v to the ssh command, this is what I got:

```
OpenSSH_7.6p1, LibreSSL 2.6.2
debug1: Reading configuration data /Users/realideasman/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: Connecting to chantal.local port 22.
debug1: Connection established.
debug1: identity file /Users/realideasman/.ssh/id_ed25519 type 3
debug1: key_load_public: No such file or directory
debug1: identity file /Users/realideasman/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6
debug1: match: OpenSSH_7.6 pat OpenSSH* compat 0x04000000
debug1: Authenticating to chantal.local:22 as 'chantal'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:qdSsyPIeGrFRjhGBNIzJTAUSLC7HMhxh5IMPr4gm6oE
No ECDSA host key is known for chantal.local and you have requested strict checking.
Host key verification failed.
```

**Comment by Mrwerdo** [comment]
Things that I think need fixing:
1. rename ssh_key to something more suiting.
2. fix corner cases when ssh_key is not provided or not a file.
3. make clear why ssh_key is loaded with the contents of the host's public key while it's being parsed by falk.

Most likely all of this needs to be fixed in `falk/vm/__init__.py`

**Comment by TheJJ** [comment]
I fixed 1. and 2., and for 3 i extended the example config file.

**Comment by Mrwerdo** [comment]
I've tried the latest commit: ec0ca21, but it still doesn't work. I needed to patch the changes because the custom vm provider isn't being imported and needs some fixes to make it work. 

I can submit a pull request if you'd like to use the one I'm using.

I've been trying to see why ssh is failing to connect. I've been attempting to simulate the commands using `os.system`. I just `cat`ed the UserKnownHosts file before ssh used it to connect to the vm. This is what it was:

    [chantal.local]:22 chantal.local,192.168.107.129 ecdsa-sha2-nistp256 SHA256:qdSsyPIeGrFRjhGBNIzJTAUSLC7HMhxh5IMPr4gm6oE

I previously ssh_known_host_key to `chantal.local,192.168.107.129 ecdsa-sha2-nistp256 SHA256:qdSsyPIeGrFRjhGBNIzJTAUSLC7HMhxh5IMPr4gm6oE`. Is the brackets apart of the syntax standard?

**Comment by Mrwerdo** [comment]
The IP address and hostnames use a different format: `chantal.local,192.168.107.129 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBD9aWtiDC5HDejesoP+e4/OsOwNzWDzfj0/37XRQ6HGR1L/L4Z8P6d4j5FDa1GungHvQbBfa1m/w+/ceDfdvLms=`.

The version of ssh I'm using is: OpenSSH_7.6p1, LibreSSL 2.6.2, which is the default macOS one found at /usr/bin/ssh

**Comment by TheJJ** [comment]
I think the issues are now fixed, it supports both formats now (of a `known_hosts` file and a `/etc/ssh/ssh_host_*_key.pub`). Please try again.

**Comment by Mrwerdo** [comment]
This works now, I appreciate the help and fixes a lot.
